# Física computacional

## Práctica 1. Python para físicos

En esta práctica haremos uso de las principales herramientas del lenguaje Python.

Procedimiento. Abra este archivo [Practi-01.ipynb] con Jupyter. Una vez que esté leyendo esto en Jupyter, realice los ejercicios  propuestos. 

## 1. Introducción

Instrucciones básicas: Cada cuadro que aparece para editar, como éste:

Es un cuadro que permite la introducción de código Python y para ejecutar solo tenemos que presionar 'shift + enter' (en las prácticas se va obviar pedir que se presionen estas teclas). La primera función de python que vamos a usar es

esta función imprime en pantalla en valor de la variable a. Usemosla: primero defina una variable llamada 'yo' cuyo contenido sea su nombre (recuerde que las cadenas en python se definen entre comillas Ej. "cadena").

In [1]:
yo = 'Hiram'

Imprima el valor de la variable yo usando la función print.

In [2]:
print (yo)

Hiram


En python las variables son dinámicas, es decir no tienen un tipo definido. De esta manera podemos cambiarle el valor a la variable yo y ponerle por ejemplo un valor numérico. Asigne su edad en años a la variable yo.

In [3]:
yo = 22

Existe tres tipos principales de variables que usamos en cálculos físicos, a saber enteros, flotantes y complejos. Defina una variable llamada entero con valor igual al año en que ingresó a la universidad; una variable llamada flotante con valor cercano a pi (con los decimales que se acuerde) y una variable llamada complejo cuya parte real sea el valor de la variable entero y la parte imaginaria el valor de flotante (para de denotar la parte imaginaria se pone j después del número) .

In [4]:
entero = 2014
pi = 3.141592
complejo = 3 + 7j

Existen convertidores entre estos tipos de variable, estas funciones son: int, float y complex. Averigue con funcionan, preguntando aquí en jupyter, para esto use el simbolo ? después de la funcion.

In [5]:
int?

In [6]:
float?

In [7]:
complex?

Operaciones Aritméticas:

Existen otras operaciones útiles:

apliquemos las siguiente operaciones, considere un paralelepipedo de largo 5.3 ancho 4 y alto 10. Encuentre el area de la cara más pequeña.

In [8]:
largo = 5.3
ancho = 4.
alto = 10.

In [9]:
ancho*largo

21.2

In [10]:
volumen = ancho*largo*alto
volcubo = ancho**3.
dif = volumen - volcubo

print(volumen)
print(dif)

212.0
148.0


Si se asigna el resultado de una operación a una variable esta tendrá el tipo más general de las variables involucradas en la operación. Ejemplifique lo anterior.

In [11]:
entero = 4
flotante = 3.2
print entero*flotante

12.8


¿Que hace la siguiente sentencia?:

Averiguelo probando aquí:

In [12]:
x=0
x=x+1

y escriba su conclusión aquí: Suma uno al valor de la variable x que teniamos anteriormente

 A continuación mostraremos algunos modificadores, después de mostrarlos usted debe encontrar su función experimentado y después  escribir su conclusión en la celda de escritura.

In [13]:
x+=1
print x

x+=3
print x

2
5


Sirve para:

Sirve para sumar el valor que quieras a la variable x, por ejemplo si usamos x+=1, se suma uno a la variable, s escribimos x+=5 se suma cinco, etc. 

In [14]:
x-=2
print x
x-=1
print x

3
2


Resta a la variable x el valor que indiquemos

In [15]:
x *= -10
print x
x *= 3.10
print x

-20
-62.0


Multiplica la variable x por el valor indicado después del *=

In [16]:
x /= 4.5
print x

-13.7777777778


Divide la variable x entre el número indicado

In [17]:
x//=3
print x

-5.0


Nos da el valor entero de la división de la variable x entre el número que se asigne

Averigue que hace la siguiente sentencia   x,y =y,x

In [18]:
x = 3
y = 4
x,y=y,x

print x,y

4 3


Intercambia los valores de x e y

Para preguntar al usuario un valor se puede usar la función input, se usa así

#### Pelota lanzada desde una torre.

Considere una pelota lanzada desde una torre de altura $h$. Tiene velocidad inicial cero y se acelera hacia abajo debido a la gravedad (que tomamos como $g=9.81$ $ms^-1$). Ignorando la fricción del aire, encuentre la altura de la pelota a un tiempo $t$.

Para solucionar este problema escribiremos un programa que pida al usuario la altura del edificio y el tiempo al que quiere saber la altura de la pelota e imprima al altura de la pelota a ese tiempo

In [19]:
def caida():
    g = 9.81
    h = input('Altura:')
    t = input('Tiempo:')
    y = h-0.5*g*t**2.
    return y
    


Usando su código anterior, encuentre la altura de una pelota que es lanza desde 100 metros a t=1 s. Escriba su resultado.

In [20]:
caida()

Altura:100
Tiempo:1


95.095

Usando su código anterior, encuentre la altura de una pelota que es lanza desde 100 metros a t=5 s. Escriba su resultado.

In [21]:
caida()

Altura:100
Tiempo:5


-22.625

Explique su resultado.

En el primer resultado vemos que la pelota cayó aproximadamente 5 metros en el tiempo transcurrido, en el segundo ejemplo tenemos un valor negativo, ésto nos indica que el tiempo que utilizamos es mayor al tiempo de caida de la pelota.

Para arreglar su programa vamos a usar el condicional if. Este funciona de la siguiente manera:

In [22]:
def caida():
    g = 9.81
    h = input('Altura:')
    t = input('Tiempo:')
    y = h-0.5*g*t**2.
    if y<0:
        y=0
        print 'El tiempo utilizado es mayor que el tiempo de caida'
    return y

donde expresion refiere a una condición, para estas generalmente se usan los siguientes operadores ==, <, > <=, >=, !=

Note que en python no necesitamos decir dónde termina el codigo para cada condicional, esto se especifica con la identación. Usando el condicional if reescriba su programa para la caída de la pelota para que no arroje números negativos e informe al usuario.

#### Ciclos en Python

En python hay solo dos tipos de loops o ciclos y son los ciclos while y los ciclos for. El primero es:

El bloque de código se ejecutará mientras se cumpla la condición (mientras sea verdadera). Escriba un codigo que sume todos los numeros pares del 1 al 500 y que imprima el resultado.

In [23]:
x = 0
for i in range(1,501):
    if i%2==0:
        x+=i

print x
    
    

62750


El otro tipo de ciclo es el que ofrece for. Este tipo de ciclos es muy versatil, se basa en las listas (un tipo de variable en python) y funciona así:

El bloque de código se ejecutará mientras no acabe de recorrer la lista. El valor de variable será el item de la lista que está siendo tratado en el momento. Ejemplo:

la función range retorna una lista de números según los parámetros de entrada: En este caso, range está generando una lista que va desde -9 hasta 9 (un número antes del segundo parámetro). La lista de números generada por range se representa así: [-9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9] El código de ejemplo imprimirá los números del -9 al 9.

In [24]:
for i in range(-9, 10):
    print i

-9
-8
-7
-6
-5
-4
-3
-2
-1
0
1
2
3
4
5
6
7
8
9


#### Ejercicios

1.- Considera una pelota lanzada desde una torre de altura $h$ y con velocidad inicial cero. Escriba un programa que pregunte al usuario la altura de la torre y diga el tiempo que tardará en caer la pelota.

In [25]:
def tiempo():
    g = 9.81
    h = input('Altura:')
    t = (2.*h/g)**(0.5)
    return t

2.- Se lanzará un satelite para que realice una órbita circular alrededor de la tierra de manera tal que su periodo es de $T$ segundos.
- Encuentre una expresión para la altura a la cual debe estar el satelite. Considere $G=6.67\times 10^{-11}$ $m^{3}kg^{-1}s^{-2}$, la masa dela tierra $M=5.07\times 10^{24}$ $Kg$  y $R=6371$ $Km$ su radio. Escriba su resultado aquí, puede usar codigo latex (usando el marcador \$)

De la tercera ley de Kepler $h = \sqrt[3]{\frac{G}{4\pi^2}MT^2}$, con respecto al centro de la Tierra, para el resultado con respecto a la superficie sería $h = \sqrt[3]{\frac{G}{4\pi^2}MT^2}-R$


- Escriba un programa que pregunte al usuario el valor deseado de $T$ y calcule e imprima la altura correcta en metros.

In [26]:
import numpy as np
def altura():
    G = 6.67E-11
    M = 5.07E24
    R = 6371000. #en metros
    T = input('Periodo:')
    h = (G*M*T**2./(4*np.pi**2.))**(1./3.)-R
    return h

- Use su programa para calcular la altura de las órbitas geosincronas aquellas que realizan una vuelta en un día. 

In [27]:
altura()

Periodo:86400


33617383.38027233

- Use su programa para calcular la altura de una órbita de 90 minutos y una de 45 minutos. ¿Qué concluye de estos resultados? 

In [28]:
altura()

Periodo:5400


-73224.25349107385

In [29]:
altura()

Periodo:2700


-2403649.8847280024

Para los periodos de 90 y 45 minutos obtuvimos una altura negativa con respecto de la superficie Terrestre, nos indica que para que estos satelites pudieran orbitar con tal periodo tendrían que estar dentro de la Tierra lo cual no es posible pues caerían al piso por la aceleración de la gravedad.

- si es necesario usando condicionales para reescribir su programa.

In [30]:
def altura():
    G = 6.67E-11
    M = 5.07E24
    R = 6371000. #en metros
    T = input('Periodo:')
    h = (G*M*T**2./(4*np.pi**2.))**(1./3.)-R
    if h<0:
        print 'No es posible una orbita para este periodo'   
    return h

- Técnicamente un satelite geosíncrono es aquel que orbita la tierra una vez cada día sideral, que es 23.93 horas, no cada 24. ¿Porqué es esto? y ¿Qué diferencia daría esto en altitud?

In [31]:
sideral = altura()
dia24 = altura()

Periodo:86400
Periodo:23.93*60*60


In [32]:
abs(sideral - dia24)

77793.03664834797

La diferencia entre el día sideral con el día trópico, se debe al movimiento de traslación de la Tierra en su orbita con el Sol. Pues un día sideral es el tiempo que dar una vuelta sobre su propio eje independientemente de la posición del Sol en el cielo, mientras que el día solar se define cuando el Sol vuelve a un mismo punto aparente en el cielo después de un día, pero durante este día la Tierra adelanto un segmento de su órbita causando que el Sol este desplazado si consideraramos el día sideral, la diferencia es de aproximadamente 4 minutos.


3.- Usando ciclos aproxime el valor de $\sqrt{3}$, usando la evaluación iterativa de la siguiente expresión $x=(x+3/x)/2$ iniciando con x=1. El código debe imprimir el valor en cada iteración. 

In [33]:
x=1.
for i in range(1,11):
    x = (x+3./x)/2.
    print x

2.0
1.75
1.73214285714
1.73205081001
1.73205080757
1.73205080757
1.73205080757
1.73205080757
1.73205080757
1.73205080757


## 2.- Paquetes y modulos para matemáticas y matrices

Existen operaciones además de las aritméticas que vamos a necesitar en nuestras simulaciones, estas no están definidas defacto en python, sin embargo podemos usarlas si tan solo la importarmos del paquete y modulo apropiado. Por ejemplo supongamos que queremos calcular el error de nuestro cálculo de $\sqrt{3}$ en el ejercicio anterior. Entonces tendríamos que comparar nuestra aproximación con el cálculo de función intrínseca. 

Para usar la función para sacar raiz primero la importamos así

Modifique el ejercicio anterior para que imprima el error en cada iteracción con respecto a la función intrínseca de python.

In [34]:
from math import sqrt
x=1.
for i in range(1,11):
    x = (x+3./x)/2.
    print x,abs((x-sqrt(3))/sqrt(3))



2.0 0.154700538379
1.75 0.0103629710818
1.73214285714 5.31448463162e-05
1.73205081001 1.41211226504e-09
1.73205080757 0.0
1.73205080757 0.0
1.73205080757 0.0
1.73205080757 0.0
1.73205080757 0.0
1.73205080757 0.0


El paquete math contiene la mayoría de las funciones básicas incluyendo: log, log10, exp, sin, cos, tan, atan, acos, atan. sinh, cosh, tanh, sqrt, etc. Si quiere verlas todas, visite la siguiente dirección __(https://docs.python.org/2/library/math.html)__ . si se quiere importar todas las funciones de un modulo se usa la siguiente expresión.

Usemos estas funciones: Escriba un código que pregunte al usuario las coordenadas cartesianas $(x,y)$ y que arroje su representación en polares $(r,\theta)$. 

In [35]:
from math import *
def polar():
    x = input('Coordenada X:')
    y = input('Coordenada Y:')
    r = sqrt(x**2.+y**2.)
    if x>0 and y>=0:
        theta = atan(1.*y/x)
    elif x==0 and y>=0:
        theta = pi/2
    elif x<0:
        theta = atan(1.*y/x) + pi
    elif x==0 and y <0:
        theta = 3.*pi/2.
    elif x>0 and y<0:
        theta = atan(1.*y/x)+2.*pi
    print 'la representacion polar es:(%f,%f)'%(r,theta)
    

In [36]:
polar()

Coordenada X:4.5
Coordenada Y:6.1
la representacion polar es:(7.580237,0.935211)


Escriba un código que hago la transformación inversa: pregunte al usuario la representación en polares $(r,\theta)$ y arroje las coordenadas cartesianas $(x,y)$. 

In [37]:
from math import *
def cartesiana():
    r = input('Coordenada r:')
    theta = input('Coordenada theta (radianes):')
    x = r*cos(theta)
    y = r*sin(theta)
    print 'la representacion cartesiana es:(%f,%f)'%(x,y)

In [38]:
cartesiana()

Coordenada r:7.580237
Coordenada theta (radianes):0.935211
la representacion cartesiana es:(4.499997,6.100001)


### Matrices

Las matrices las vamos a tratar usando el paquete numpy (numerical python), de maner ageneral existe dos maneras de importar funciones, por ejemplo si queremos usar la función array, podemos hacer dos cosas:

O bien

Usando array defina un vector columna $Vc$ de dimensión 4, un vector renglon $Vr$ de dimension 5 y una matrix $A$ de 3x3 con valores cualesquiera.

In [39]:
import numpy as np
Vc = np.array([[1.],[2.],[3.],[4.]])
Vr = np.array([[1.,2.,3.,4.,5.]])
A = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])

Defina otra matriz de 3x3 B, y aplique las funciones aritméticas básicas con la matriz A.

In [40]:
B = np.array([[4.,3.,1.],[7.,9.,3.],[5.,4.,2.]])

print A+B
print A-B
print A*B
print A/B

[[  5.   5.   4.]
 [ 11.  14.   9.]
 [ 12.  12.  11.]]
[[-3. -1.  2.]
 [-3. -4.  3.]
 [ 2.  4.  7.]]
[[  4.   6.   3.]
 [ 28.  45.  18.]
 [ 35.  32.  18.]]
[[ 0.25        0.66666667  3.        ]
 [ 0.57142857  0.55555556  2.        ]
 [ 1.4         2.          4.5       ]]


¿Cómo se accesa a los valores de la matriz? supongamos que se quiere extraer el elemento 1,3 de A ¿Cómo se hace? Averigue y reporte sus resultados


Para buscar el elemento que se quiere de una matriz se escribe el nombre de la matriz y las coordenadas quje se desean, es decir A[i,j], siendo i el renglon y j la columna, es importante saber que i y j deben ir de 0 a N-1 con N-1 el rango de la matriz

In [41]:
print A[1,2]
print A[0,0]
print A[2,2]

6.0
1.0
9.0


IMPORTANTE: (1) seguro ya notó que la numeración de los arreglos va de 0 a N-1, con N-1 el rango de la matriz. (2) cuando se usa la siguiente sentencia Matriz_A=MatrizB python no crea dos variables si no que la matriz_A se vuelve una referencia de matriz_B, esto se puede cambiar haciendo por ejemplo matriz_A=1.\*matriz_B o bien con la función copy.